%YAML:1.0

#common parameters
project_rootdir: "/home/hugoliu/github/catkin_ws/src/VIW-Fusion/"
can_name: "vcan0"  #"vcan0" for socketcan or "0" for usbcan

mr415_det_topic: "mr415_detection"
mr415_marker_topic: "mr415_markers"

image_width: 1920
image_height: 1080
pixel_size_um: 2.8
lens_efl_mm: 2.666

#pixel_size = 2.8um, lens_efl = 2.666mm
k_front: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [952.1,  0.0,     960.0,
         0.0,    952.1,   540.0,
         0.0,    0.0,     1.0  ]

# distortion kb model, [k1, k3] = [2.66822668, -0.18649677]
d_kb: !!opencv-matrix
  rows: 2
  cols: 1
  dt: d
  data: [2.668,
         -0.186]

# x-forward, +1.0 means radar is front of camera 1.0m
# y-left, +1.0 means radar on the left of camera 1.0m
# z is camera height, radar don't need z, -1.3 means camera height 1.3m
t_radar_to_camera: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.0,
         0.0,
         -1.3]

# euler angles in right-hand, pitch: +Y, roll: +X, yaw: -Z
# pitch: + means radar is looking down
# roll: + means radar is tilting right
# yaw: + means radar is looking right
euler_radar_to_camera: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.0,
         0.0,
         0.0]
